# Generated by Django 4.0.6 on 2022-08-20 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_book_request_req_status_book_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='userImg/'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
