# Generated by Django 4.0.6 on 2022-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_reader_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='userImg'),
        ),
    ]
