# Generated by Django 4.1.6 on 2023-02-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_book_review_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_rating',
            name='book_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.book_review'),
        ),
    ]
