# Generated by Django 4.1.6 on 2023-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_rating_book_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_rating',
            name='book_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Book_review',
        ),
    ]
