# Generated by Django 4.1.6 on 2023-03-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_book_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_highlight',
            name='is_public',
            field=models.BooleanField(default=1),
        ),
    ]
